In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("demographic.csv")

In [4]:
df.columns # to check columns in our data

Index(['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN',
       'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'RIDEXAGM', 'DMQMILIZ', 'DMQADFC',
       'DMDBORN4', 'DMDCITZN', 'DMDYRSUS', 'DMDEDUC3', 'DMDEDUC2', 'DMDMARTL',
       'RIDEXPRG', 'SIALANG', 'SIAPROXY', 'SIAINTRP', 'FIALANG', 'FIAPROXY',
       'FIAINTRP', 'MIALANG', 'MIAPROXY', 'MIAINTRP', 'AIALANGA', 'DMDHHSIZ',
       'DMDFMSIZ', 'DMDHHSZA', 'DMDHHSZB', 'DMDHHSZE', 'DMDHRGND', 'DMDHRAGE',
       'DMDHRBR4', 'DMDHREDU', 'DMDHRMAR', 'DMDHSEDU', 'WTINT2YR', 'WTMEC2YR',
       'SDMVPSU', 'SDMVSTRA', 'INDHHIN2', 'INDFMIN2', 'INDFMPIR'],
      dtype='str')

In [5]:
df['RIDAGEYR']

0        69
1        54
2        72
3         9
4        73
         ..
10170    26
10171     2
10172    42
10173     7
10174    11
Name: RIDAGEYR, Length: 10175, dtype: int64

In [6]:
df['RIDAGEYR'].mean()

np.float64(31.484127764127763)

In [10]:
df['DMDHSEDU'].unique()

array([nan,  1.,  3.,  4.,  5.,  2.,  9.,  7.])

In [12]:
df['DMDEDUC2'].unique() # categorical ordered

array([ 3.,  4., nan,  5.,  2.,  1.,  9.,  7.])

In [13]:
df['RIAGENDR'].unique() # categorical unordered

array([1, 2])

# One Hot Encoding

In [14]:
B = ['bird', 'cat', 'dog', 'cat', 'bird', 'bird']
d = {'Categorical': B}
df = pd.DataFrame(d)

In [15]:
df

  Categorical
0        bird
1         cat
2         dog
3         cat
4        bird
5        bird

In [23]:
# "dummies" is used to create columns corresponding to unique values
dfDummies = pd.get_dummies(df['Categorical'], prefix= 'category', dtype=int)

In [24]:
dfDummies

   category_bird  category_cat  category_dog
0              1             0             0
1              0             1             0
2              0             0             1
3              0             1             0
4              1             0             0
5              1             0             0

In [25]:
dfDummies.values # one hot representation

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])